spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix=2
        - id: carts-service
          uri: lb://carts-service
          predicates:
            - Path=/api/cart/**
          filters:
            - StripPrefix=2
    loadbalancer:
      retry:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080

